### ISSUE TITLE
undefined method `write_timeout=' for #<StubSocket:

### ISSUE THREAD

**Issue by masterkain** [drbrain/net-http-persistent#108]
I upgraded from 3.0.1 to 3.1.0 and I have this error while running specs during a VCR replay and sometimes record.

rspec -> stripe -> faraday -> net-http-persistent

```
      # /usr/local/bundle/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:659:in `connection_for'
      # /usr/local/bundle/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/adapter/net_http_persistent.rb:38:in `perform_request'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/request/multipart.rb:15:in `call'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
      # /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/stripe_client.rb:185:in `block in execute_request'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/stripe_client.rb:266:in `execute_request_with_rescues'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/stripe_client.rb:184:in `execute_request'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/api_operations/request.rb:19:in `request'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/api_operations/request.rb:49:in `request'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/api_resource.rb:96:in `refresh'
      # /usr/local/bundle/gems/stripe-4.21.3/lib/stripe/api_resource.rb:103:in `retrieve'
      # ./app/models/account.rb:481:in `stripe_customer'
```

**Comment by masterkain** [comment]
most likely an issue with webmock https://github.com/bblimke/webmock/blob/8820c9d23f169af35ca2348036d76a15c8ce71d5/lib/webmock/http_lib_adapters/net_http.rb#L237
