### ISSUE TITLE
ArgumentError: bad argument (expected URI object or URI string) with Bundler 2.1.4

### ISSUE THREAD

**Issue by utkarsh2102** [drbrain/net-http-persistent#116]
Hi there,
When building net-http-persistent against bundler 2.1.4, I get the following backtrace:

```
ArgumentError: bad argument (expected URI object or URI string)
  /usr/lib/ruby/2.5.0/uri/common.rb:745:in `URI'
  /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:954:in `request'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/downloader.rb:59:in `request'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/downloader.rb:17:in `fetch'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:131:in `call'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/compact_index_client/updater.rb:53:in `block in update'
  /usr/lib/ruby/2.5.0/tmpdir.rb:93:in `mktmpdir'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/compact_index_client/updater.rb:31:in `update'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/compact_index_client.rb:98:in `update'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:75:in `available?'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:16:in `call'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher.rb:162:in `use_api'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `block in api_fetchers'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `select'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:388:in `api_fetchers'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:393:in `block in remote_specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/index.rb:11:in `build'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:392:in `remote_specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/rubygems.rb:88:in `specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:273:in `block (2 levels) in index'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:271:in `each'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:271:in `block in index'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/index.rb:11:in `build'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:268:in `index'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:258:in `resolve'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:158:in `resolve_remotely!'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/installer.rb:303:in `resolve_if_needed'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/installer.rb:84:in `block in run'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/installer.rb:73:in `run'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/installer.rb:25:in `install'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli/install.rb:66:in `run'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:256:in `block in install'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/settings.rb:124:in `temporary'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:255:in `install'
  /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
  /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
  /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
  /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
  /usr/bin/bundle:23:in `load'
  /usr/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby2.5
  Config Dir  /etc
RubyGems      2.7.6.2
  Gem Home    /tmp/autopkgtest-lxc.ju6ha8au/downtmp/build.JtB/src/tmp/gempath/ruby/2.5.0
  Gem Path    /tmp/autopkgtest-lxc.ju6ha8au/downtmp/build.JtB/src/tmp/gempath/ruby/2.5.0
  User Home   /home/debci
  User Path   /home/debci/.gem/ruby/2.5.0
  Bin Dir     /tmp/autopkgtest-lxc.ju6ha8au/downtmp/build.JtB/src/tmp/gempath/ruby/2.5.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1d  10 Sep 2019
  Loaded      OpenSSL 1.1.1d  10 Sep 2019
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.25.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/bin/ruby2.5
bundle #!     /usr/bin/ruby
```

**Comment by drbrain** [comment]
Please file this against bundler, as it has a vendored version of this library.

Additionally, if the URI bundler is building and trying to fetch is invalid there's nothing this library can do.
