### ISSUE TITLE
Net::HTTP::Persistent::Error: too many connection resets

### ISSUE THREAD

**Issue by treeder** [drbrain/net-http-persistent#37]
This was reported a while back, but it was closed so making a new one: https://github.com/drbrain/net-http-persistent/issues/19

We get this error a LOT and from searching around the web, it seems other people get it too and they all seem to trace back to net-http-persistent (http://goo.gl/c1Qes). We recently had a user who was getting this pretty consistently, and easily, from a heroku app so we had him try changing the backing gem to rest-client and typhoeus and the problem disappeared using either of those. All our gems are using the 'rest' gem (https://github.com/iron-io/rest) so we just had the user change the backing gem like so:

``` ruby
    Rest::Client.new(:gem=>:typhoeus)
```

Here are some examples of what we're seeing on a regular basis, all of these from today:

```
Net::HTTP::Persistent::Error: too many connection resets (due to end of file reached - EOFError) after 0 requests on 73380140, last used 1363039742.9996092 seconds ago

Net::HTTP::Persistent::Error: too many connection resets (due to end of file reached - EOFError) after 0 requests on 82025000, last used 1363039458.9997427 seconds ago

Net::HTTP::Persistent::Error: too many connection resets (due to end of file reached - EOFError) after 1 requests on 28986080, last used 59.305080555 seconds ago -- ["/usr/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:959:in 

too many connection resets (due to end of file reached - EOFError) after 16 requests on 34995740, last used 0.059532367 seconds ago
```

And so on. All on the same line it appears:

```
/usr/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:959:in `rescue in request'
/usr/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:968:in `request'
```

It would be great if we could find a fix because I really like your library, it performs almost as good as typhoeus with no binary dependency which is great.

**Comment by tilo** [comment]
@drbrain encountering the same error when using Gem-in-a-box 
https://github.com/geminabox/geminabox/issues/211

**Comment by brucek** [comment]
I see this issue very reliably when using [neo4jrb](https://github.com/neo4jrb/neo4j-core) 6.1.5 and [resque-pool](https://github.com/nevans/resque-pool) 0.6.0.

In my Rails 4.2 project, I have a `resque.rake` file with:

```ruby
require 'resque/tasks'
require 'resque/pool/tasks'

task "resque:setup" => [:environment]

task "resque:pool:setup" do
  # close any sockets or files in pool manager
  Neo4j::Session.current.close
  cfg = Rails.application.config.neo4j

  # and re-open them in the resque worker parent
  Resque::Pool.after_prefork do |job|
    $redis.client.reconnect
    Neo4j::Session.open(cfg.session_type, cfg.session_path, cfg.session_options.merge( { name: "neo4j_#{Process.pid}",
                                                                                         default: true }))
    
    puts "#{__FILE__}:#{__LINE__}"
    p Neo4j::Session.current
    p Category.all.result.count

    # Cleanup just in case
    at_exit do
      Neo4j::Session.current.close
    end
  end
end
```

When I switch the `neo4j` `Faraday` adapter to `Typhoeus`, the problem instantly vanishes.

**Comment by brucek** [comment]
For completeness, errors I see look like this (a bunch removed - almost all are the "too many bad responses" errors):

```
/Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_response.rb:188:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_response.rb:188:in `set_data'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_response.rb:221:in `create_with_no_tx'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_session.rb:218:in `block in _query'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_session.rb:211:in `_query'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-core/query.rb:244:in `response'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-core/query.rb:308:in `pluck'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-7.2.3/lib/neo4j/active_node/query/query_proxy_enumerable.rb:85:in `pluck'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-7.2.3/lib/neo4j/active_node/query/query_proxy_enumerable.rb:24:in `result'
	from /usr/local/share/workspace/havn/lib/tasks/resque.rake:20:in `block (2 levels) in <top (required)>'
	from (eval):12:in `block in call_after_prefork!'
	from (eval):11:in `each'
	from (eval):11:in `call_after_prefork!'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:415:in `block in spawn_worker!'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:411:in `fork'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:411:in `spawn_worker!'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:389:in `block in spawn_missing_workers_for'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:388:in `times'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:388:in `spawn_missing_workers_for'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:374:in `block in maintain_worker_count'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:372:in `each'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:372:in `maintain_worker_count'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:284:in `start'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:109:in `run'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool/tasks.rb:17:in `block (2 levels) in <top (required)>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
	from /Users/bruce/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool/cli.rb:185:in `start_pool'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool/cli.rb:21:in `run'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/bin/resque-pool:7:in `<top (required)>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/resque-pool:23:in `load'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/resque-pool:23:in `<main>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/ruby_executable_hooks:15:in `<main>'
/Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:1012:in `rescue in request': too many bad responses after 39 requests on 70214162798040, last used 1.181841 seconds ago (Net::HTTP::Persistent::Error)
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:1038:in `request'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:25:in `perform_request'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:21:in `with_net_http_connection'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday_middleware-0.10.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_session.rb:50:in `open'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j-server/cypher_session.rb:6:in `block in <module:Server>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j/session.rb:125:in `create_session'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/neo4j-core-6.1.5/lib/neo4j/session.rb:110:in `open'
	from /usr/local/share/workspace/havn/lib/tasks/resque.rake:14:in `block (2 levels) in <top (required)>'
	from (eval):12:in `block in call_after_prefork!'
	from (eval):11:in `each'
	from (eval):11:in `call_after_prefork!'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:415:in `block in spawn_worker!'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:411:in `fork'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:411:in `spawn_worker!'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:389:in `block in spawn_missing_workers_for'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:388:in `times'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:388:in `spawn_missing_workers_for'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:374:in `block in maintain_worker_count'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:372:in `each'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:372:in `maintain_worker_count'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:307:in `block in join'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:301:in `loop'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:301:in `join'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool.rb:109:in `run'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool/tasks.rb:17:in `block (2 levels) in <top (required)>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
	from /Users/bruce/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool/cli.rb:185:in `start_pool'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/lib/resque/pool/cli.rb:21:in `run'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bundler/gems/resque-pool-2eb1944741be/bin/resque-pool:7:in `<top (required)>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/resque-pool:23:in `load'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/resque-pool:23:in `<main>'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bruce/.rvm/gems/ruby-2.3.1@havn/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by MatzFan** [comment]
Just a ping to see if any progress was being made on this issue? I am seeing the following with a GET request using Mechanize via Tor while trying to get a new identity by restarting Tor service.
```
 Net::HTTP::Persistent::Error:
       too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 1 requests on 47284442234660, last used 0.081786187 seconds ago
```
A flaky `sleep 1` after Tor restart seems to fix it, so I may try [an alternative workaround](http://scottwb.com/blog/2013/11/09/defeating-the-infamous-mechanize-too-many-connection-resets-bug/)

**Comment by drbrain** [comment]
@MatzFan this is always due to network issues so you'll need to perform workarounds outside this library

**Comment by MatzFan** [comment]
Understood - thanks @drbrain

**Comment by chewi** [comment]
No one has yet commented on the fact that the "last used seconds ago" value is sometimes ludicrously high. While writing this, it suddenly twigged that these values point to the UNIX epoch, `1970-01-01 00:00:00`! Not a real problem but you might want to tweak that message. :grin:

**Comment by grosser** [comment]
possibly fixed by removing retry logic, please comment on https://github.com/drbrain/net-http-persistent/pull/100 if you are interested
